//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppiController.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peliculas
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string genero { get; set; }
        public string director { get; set; }
        public Nullable<System.DateTime> emicion { get; set; }
    }
}
